[package]
name = "create_key_addr"
version = "0.1.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
cita-crypto = { path = "../../share_libs/crypto" }
util = { path = "../../share_libs/util" }
