language: generic
sudo: required
cache:
  timeout: 600
  directories:
    - $TRAVIS_BUILD_DIR/target/debug
    - /opt/.cargo/git
    - /opt/.cargo/registry
services:
  - docker
git:
  depth: 1
stages:
  - Release
  - IntegrateTest
before_install:
  - docker pull cita/cita-build:ubuntu-18.04-20190107
jobs:
  include:

    - stage: Release
      name: Release for Integrate Test
      language: node_js
      node_js:
        - lts/*
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/target/release-cache
      env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
      before_script:
        - cd $TRAVIS_BUILD_DIR
        - ./scripts/replace_default_feature.sh ./ sha3hash  ${HASH_ALGO}
        - ./scripts/replace_default_feature.sh ./ secp256k1 ${CRYPTO_ALGO}
      script: ./env.sh make release
      before_cache:
        - cd $TRAVIS_BUILD_DIR
        - rm -rf target/release-cache
        - mv -vf target/install target/release-cache

    - &stage-contract-test-sha3-secp256k1
      stage: IntegrateTest
      name: Unit Group
      language: node_js
      node_js:
        - lts/*
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/target/release-cache
      env: HASH_ALGO=sha3hash    CRYPTO_ALGO=secp256k1
      before_install:
        - cd $TRAVIS_BUILD_DIR
        - rm -rf target/install
        - cp -rv target/release-cache target/install
      install:
        - rm -rf /opt/cita-run/test-chain
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./env.sh ./scripts/create_cita_config.py create
            --nodes "127.0.0.1:4100"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./env.sh ./bin/cita setup test-chain/0
        - ./daemon.sh ./bin/cita start test-chain/0
      before_script:
        - cd $TRAVIS_BUILD_DIR/target/install/scripts/contracts/tests
        - travis_retry yarn install
      script: npm run-script unit_group
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Permission
      script: npm run-script unit_permission
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Auth
      script: npm run-script unit_auth
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Chain
      script: npm run-script unit_chain
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Group Management
      script: npm run-script unit_gm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Permission Management
      script: npm run-script unit_pm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Role Management
      script: npm run-script unit_rm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Quota Management
      script: npm run-script unit_qm
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Abi
      script: npm run-script abi
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Admin
      script: npm run-script unit_admin
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Store
      script: npm run-script store
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Batch Tx
      script: npm run-script batch_tx
    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Uint8
      script: npm run-script uint8

    - <<: *stage-contract-test-sha3-secp256k1
      name: Unit Node
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./env.sh ./scripts/create_cita_config.py create
            --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - for i in {0..2} ; do
             ./env.sh bin/cita setup test-chain/$i
             && ./daemon.sh bin/cita start test-chain/$i ;
          done
      script:
        - npm run-script unit_node

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate Quota
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./env.sh ./scripts/create_cita_config.py create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.checkQuota=true"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./env.sh ./bin/cita setup test-chain/0
        - ./daemon.sh ./bin/cita start test-chain/0
      script:
        - npm run-script integrate_quota

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate Permission
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./env.sh ./scripts/create_cita_config.py create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.checkCallPermission=true"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./env.sh ./bin/cita setup test-chain/0
        - ./daemon.sh ./bin/cita start test-chain/0
      script:
        - npm run-script permission

    - <<: *stage-contract-test-sha3-secp256k1
      name: Integrate AutoExec
      install:
        - cd $TRAVIS_BUILD_DIR/target/install
        - ./env.sh ./scripts/create_cita_config.py create
            --nodes "127.0.0.1:4100"
            --contract_arguments "SysConfig.autoExec=true"
            --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"
        - ./env.sh ./bin/cita setup test-chain/0
        - ./daemon.sh ./bin/cita start test-chain/0
      script:
        - npm run-script auto_exec
