language: rust
cache:
  cargo: true
rust: nightly-2017-08-04
dist: trusty
sudo: true
jobs:
  include:
    - stage: build & test1
      script:
        - |
          set -e
          echo '################################################################################'
          echo '1) setup'
          scripts/install_develop.sh
          scripts/config_rabbitmq.sh
          echo '################################################################################'
          echo '2) format'
          make fmt
          echo '################################################################################'
          echo '3) build'
          make debug
          echo '################################################################################'
          echo '4) unit test'
          make test
