[workspace]
members = ["auth"
,"tokio-jsonrpc"
,"jsonrpc"
,"chain"
,"consensus/tdmint"
,"network"
,"tools/create_key_addr"
,"tools/monitor"
,"tests/trans_evm"
,"tests/chain_performance"
,"tests/amqp"
,"tests/latency"
,"tests/jsonrpc_performance"
,"tests/benchmark_ws"
,"tests/chain_performance_by_mq"
]

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'
