[workspace]
members = ["auth"
,"jsonrpc"
,"chain"
,"consensus/tdmint"
,"consensus/txpool"
,"consensus/raft"
,"consensus/authority_round"
,"network"
,"tools/create_key_addr"
,"tests/trans_evm"
,"tests/chain_performance"
,"tests/amqp"
,"tests/latency"
,"tests/jsonrpc_performance"
,"tests/benchmark_ws"
]


