
name="monitor"
command = "monitor"
pidfile = ".monitor.pid"

[[process]]
name = "auth"
command = "auth"
args = ["-c","auth.json"]
pidfile = ".auth.pid"
respawn = 3

[[process]]
name = "network"
command = "network"
args = ["-c","network.toml"]
pidfile = ".network.pid"
respawn = 3

[[process]]
name = "consensus_tendermint"
command = "consensus_tendermint"
args = ["-c","consensus.json"]
pidfile = ".consensus.pid"
respawn = 3

[[process]]
name = "jsonrpc"
command = "jsonrpc"
args = ["-c","jsonrpc.json"]
pidfile = ".jsonrpc.pid"
respawn = 3


[[process]]
name = "chain"
command = "chain"
args = ["-g","genesis.json","-c","chain.json"]
pidfile = ".chain.pid"
respawn = 3
