[package]
name = "monitor"
version = "0.1.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
toml = "0.2"
rustc-serialize = "0.3"
log = "0.3"
clap = "2"
logger = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "056d5bd" }
util = { path = "../../share_libs/util" }
