
name="monitor"
command = "./monitor"
pidfile = ".monitor.pid"

[[process]]
name = "auth"
command = "./bin/auth"
pidfile = ".auth.pid"
respawn = 3

[[process]]
name = "network"
command = "./bin/network"
args = ["-c","network.toml"]
pidfile = ".network.pid"
respawn = 3

[[process]]
name = "consensus_tendermint"
command = "./bin/consensus_tendermint"
args = ["-c","consensus.json"]
pidfile = ".consensus_tendermint.pid"
respawn = 3

[[process]]
name = "jsonrpc"
command = "./bin/jsonrpc"
args = ["-c","jsonrpc.json"]
pidfile = ".jsonrpc.pid"
respawn = 3


[[process]]
name = "chain"
command = "./bin/chain"
args = ["-g","genesis.json","-c","chain.json"]
pidfile = ".chain.pid"
respawn = 3
