[package]
name = "tx_pool"
version = "0.6.0"
authors = ["rink1969 <rink1969@cryptape.com>"]

[dependencies]
libproto = { path = "../proto" }
util = { path = "../util" }
cita-crypto = { path = "../crypto" }