[package]
name = "util"
version = "0.6.0"
authors = ["zhangsoledad <787953403@qq.com>"]

[dependencies]
libc = "0.2.20"
rustc-serialize = "0.3"
heapsize = { version = "0.3", features = ["unstable"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "0.8.0"
rand = "0.3"
sha3 = { path = "../parity/util/sha3" }
tiny-keccak= "1.0"
log = "0.3"
env_logger = "0.4"
time = "0.1"
semver = "0.6.0"
elastic-array = { git = "https://github.com/ethcore/elastic-array" }
rocksdb = { git = "https://github.com/ethcore/rust-rocksdb" }
regex = "0.1"
parking_lot = "0.4"
itertools = "0.5"
ethcore-bigint = "0.1.3"
lru-cache = "0.1.0"
ethcore-util = { path = "../parity/util" }
rlp = { path = "../../share_libs/parity/util/rlp" }
[dev-dependencies]
devtools = { path = "../../devtools" }
