[package]
description = "proto"
name = "libproto"
version = "0.6.0"
authors = ["gguoss"]

[dependencies]
protobuf = { version = "^1.0.0"}
sha3 = { path = "../parity/util/sha3"}
util = { path = "../util"}
rustc-serialize = "0.3"
bincode = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
