[package]
name = "jsonrpc"
version = "0.8.0"
authors = ["https://github.com/u2"]

[dependencies]
futures = "0.1"
hyper = "0.10"
libproto = { path = "../share_libs/proto" }
protobuf = { version = "^1.0.0" }
uuid = { version = "0.4", features = ["v4"] }
log = "0.3"
sha3 = { path = "../share_libs/parity/util/sha3"}
util = { path = "../share_libs/util"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rustc-serialize = "0.3"
amqp = "=0.0.20"
pubsub = { path = "../share_libs/pubsub" }
time = "0.1"
proof = { path = "../consensus/proof" }
docopt = "0.7"
cpuprofiler = "0.0.3"
jsonrpc_types = { path = "types" }
dotenv = "0.10.0"
transaction = { path = "../share_libs/transaction" }
cita_log =  { path = "../share_libs/cita_log" }

[[bin]]
name = "jsonrpc"
path = "src/bin/mod.rs"

[dev-dependencies]
pretty_env_logger = "0.1"
