[package]
description = "CITA node."
name = "chain"
version = "0.8.0"
authors = []

[dependencies]
libchain = {path = "libchain"}
threadpool = "1.3.2"
libproto = {path = "../share_libs/proto"}
protobuf = { version = "^1.0.0"}
log = "0.3.0"
amqp = "=0.0.20"
clap = "2"
pubsub = { path = "../share_libs/pubsub" }
util = { path = "../share_libs/util" }
state = { path = "state" }
dotenv = "0.10.0"
cita_log = { path = "../share_libs/cita_log" }

[[bin]]
path = "main.rs"
name = "chain"
