# Refer to https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml for a working example
site_name: CITA
site_url: https://github.com/cryptape/cita
site_description: 
site_author: Cryptape
repo_url: https://github.com/cryptape/cita
edit_uri: docs/docs/
remote_name: upstream

pages:
  - 中文:
    - 首页: 'zh/index.md'
    - 快速入门: 'zh/getting_started.md'
    - 主要概念:
      - 区块链: 'zh/key-concepts/blockchain.md'
      - CITA: 'zh/key-concepts/cita.md'
    - 系统组件: 'zh/components.md'
    - 使用指南:
        - Bootstrap: 'zh/usage-guide/bootstrap.md'
        - 智能合约指南: 'zh/usage-guide/smart-contract-guide.md'
        - JSON-RPC: 'zh/usage-guide/rpc.md'
        - JSON-RPC 错误码: 'zh/usage-guide/rpc_error_code.md'
        - 系统合约: 'zh/usage-guide/admintool.md'
        - 交易相关工具: 'zh/usage-guide/txtool.md'
    - 系统管理:
        - 节点管理: 'zh/system_management/node.md'
        - 权限管理: 'zh/system_management/permission.md'
        - 用户管理: 'zh/system_management/user.md'
        - 配额管理: 'zh/system_management/quota.md'
        - 日志管理: 'zh/system_management/log.md'
        - 快照: 'zh/system_management/snapshot.md'
    - 跨链:
        - 跨链合约编写及操作示例: 'zh/crosschain/crosschain_contract_example.md'
    - 架构设计: 
        - 微服务: 'zh/architecture/architecture.md'
        - 共识: 'zh/architecture/consensus.md'
        - 交易处理: 'zh/architecture/transaction_process.md'
        - 视图: 'zh/architecture/view.md'
    - 常见问题: 'zh/faq.md'
    - 附录:
      - 贡献代码: 'zh/appendix/contributing.md'
      - 词汇表: 'zh/appendix/glossary.md'

  - EN: 
    - Index: 'en/index.md'
    - 'Getting Started': 'en/getting_started.md'
    - Concepts:
      - Blockchain: 'en/key-concepts/blockchain.md'
      - CITA: 'en/key-concepts/cita.md'
    - Components: 'en/components.md'
    - 'Usage Guide':
        - Bootstrap: 'en/usage-guide/bootstrap.md'
        - 'Smart Contracts': 'en/usage-guide/smart-contract-guide.md'
        - JSON-RPC: 'en/usage-guide/rpc.md'
        - 'JSON-RPC Error Code': 'en/usage-guide/rpc_error_code.md'
        - 'System Contract': 'en/usage-guide/admintool.md'
        - 'Transaction Tool': 'en/usage-guide/txtool.md'
    - 'System':
        - Node: 'en/system_management/node.md'
        - Permission: 'en/system_management/permission.md'
        - User: 'en/system_management/user.md'
        - Quota: 'en/system_management/quota.md'
        - Log: 'en/system_management/log.md'
        - Snapshot: 'en/system_management/snapshot.md'
    - 'Cross Chain':
        - 'Cross Chain Contract Examples': 'en/crosschain/crosschain_contract_example.md'
    - Architecture: 
        - 'Micro Service': 'en/architecture/architecture.md'
        - 'Consensus': 'en/architecture/consensus.md'
        - 'Transaction Process': 'en/architecture/transaction_process.md'
        - 'View': 'en/architecture/view.md'
    - FAQ: 'en/faq.md'
    - Appendix:
      - Contributing: 'en/appendix/contributing.md'
      - Glossary: 'en/appendix/glossary.md'

theme:
  name: material
  language: zh
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  search:
    language: 'jp'
extra_css:
  - 'stylesheets/extra.css'
use_directory_urls: false

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
